### PR TITLE
Fix help_tools to read the right pedestal, masked, mip files and to r…

### PR DESCRIPTION
**Pull request by airqui**
…ead new pedestal file format including the width of the pedestal

@artlbv can you check this? I am not sure what the items[2::2] and items[2::3] was doing.

### CODE REVIEW

**Comment by artlbv** [comment]
Hi, items is the content of a line, and the items[2::2] means it's taking a subset of items starting from the 2nd (from zero), i.e. first pedestal value, and every second one.
The same for the items[3::2] starting from the 3th every second.
Since you've added another value for each sca, I guess one should only change the ::2 to ::3, but I'll check in a bit.

**Comment by airqui** [comment]
Ah, okay, then I did it completely wrong.

**Comment by artlbv** [comment]
I'll fix this in a moment after I try with the new pedestal files

**Comment by airqui** [comment]
Hi, 
I think I have it, together with few other changes, I do a new pull request and you check it, thanks.

**Comment by artlbv** [comment]
It should be like this:

```
                peds = items[2::3]
                peds_err = items[3::3]
                peds_width = items[4::3]
```

**Comment by artlbv** [comment]
By the way, I've noticed that sometimes a single SCA can have an empty pedestal value.
I believe this can be due to some statistics reason, but this should normally not be the case.
I suggest to check whether there are empty pedestals for single SCAs and assign them a pedestal equal to the average of the other SCAs.
What do you think?

**Comment by airqui** [comment]
Hi,
For the moment I have chosen to just ignore this SCA also for the signal. It can be that is just a lack of stats or that the pedestal was too bad calculated (i.e. double pedestal) and therefore is safer to ignore this sca since the problem might be also when hit bit ==1. 
Anyway, it is very reasonable to think that if we don't have stats for proper pedestal estimation, we won't have it for mip calibration.

Also remind that the information can be duplicated and maybe in other "run" we have obtained more stats and all SCAs are filled. In this case, the MIPs in  MIP_dif_1_X_X.txt are calculated using the proper pedestal values for those SCAs.

Cheers,
Adrián

**Comment by artlbv** [comment]
I've been wondering about the duplications, but then I've found your readme on the pedestals :)
https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/commit/86924286c61354f833e0be8d0380912b93ff1c28
Indeed, it seems some duplicates can have missing SCAs, while others don't. I think it would be best to store only the best estimates in the pedestal file, to avoid ambiguity since the files are used in different places. If you want I could write a quick pedestal cleaner to select already the best values to store in the file.
-Artur

**Comment by airqui** [comment]
It is not high priority to change this since the MIP analysis is already done and the fitler is in singleSlabAnalysis.cc, but it won't take long. So, as you wish.

**Pull request closed without merging**
