### PR TITLE
Refactor event building

### PR DESCRIPTION
**Pull request by kunathj**
@airqui this PR has some rather large changes, so I don't want to just silently merge it myself. As shown in the slack, the reconstructed events are significantly better after this PR.
It should probably be enough if you can just browse through the commit messages.

### CODE REVIEW

**Comment by kunathj** [comment]
Oh, and about the [macros](https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/tree/TB2022/eventbuilding/macros) folder in the eventbuilding folder: Content there seems highly out of date.
Can these files be deleted, or is it worth porting them to the new protoype?

**Comment by airqui** [comment]
> Oh, and about the [macros](https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/tree/TB2022/eventbuilding/macros) folder in the eventbuilding folder: Content there seems highly out of date. Can these files be deleted, or is it worth porting them to the new protoype?

I don't see any problem in removing the macros folder.

**Comment by airqui** [comment]
> @airqui this PR has some rather large changes, so I don't want to just silently merge it myself. As shown in the slack, the reconstructed events are significantly better after this PR. It should probably be enough if you can just browse through the commit messages.

I'll browse the commits tomorrow

**Review by airqui — COMMENTED** [review]
Sorry, I get a bit lost with the python coding... where are exactly located the pieces of code of the merging whithin chip? Are you merging only empty triggers ? Or also sca with triggers both in bcid and bcid+1 ? The latter is to be discussed with Stephane. In any case, I would not merge events in bcid and bcid+2 (or more).

Also, the "chips_with_hits>=20" seems a bit ad-hoc, although not completely unreasonable. Is the "n-layers with hit>X" not enough criteria?

**Comment by kunathj** [comment]
> I don't see any problem in removing the macros folder.

Done in [584c1a2](https://github.com/kunathj/SiWECAL-TB-analysis/commit/584c1a234e139fbb5243d7c5734a04c48238a033).

> Sorry, I get a bit lost with the python coding... where are exactly located the pieces of code of the merging whithin chip? 

This is where the SCAs are appended, if the `merge_within_chip` steering parameter is set to true:

https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/blob/584c1a234e139fbb5243d7c5734a04c48238a033/eventbuilding/bcid_handling.py#L105-L113

and here you can see what is done, if merging within chip was allowed, and if there are multiple consecutive BCIDs:

https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/blob/584c1a234e139fbb5243d7c5734a04c48238a033/eventbuilding/build_events.py#L31-L43



>Are you merging only empty triggers ? Or also sca with triggers both in bcid and bcid+1 ? 

The latter. Please have a look at the [slack message](https://calice-workspace.slack.com/archives/C038UR0DUE9/p1649079531208309) to see why I think this is necessary. Stéphane was not too surprised by having the channel triggers spread over 2 BCIDs. He blames the _Delay Box_. But both him and me have some checks in the pipeline, to confirm that this is understood (and thus, merging is ok).

>The latter is to be discussed with Stephane. 

I went to discuss with him this afternoon. Mainly on the empty events, but I also showed him this effect of hits on a chip distributed over multiple BCIDs. If I recall correctly, he said that he has not seen this before for SKIROC. But it was observed on some SPIROC (? I might be wrong here). We can try to connect with you on Zoom, after the necessary checks were performed.

>In any case, I would not merge events in bcid and bcid+2 (or more).

But would you merge _different chips_ with bcid and bcid+2 (or more)? Currently the `merge_delta` is a single number for both within-chip and between-chips. Maybe two different steering numbers would have been the better choice.

> Also, the "chips_with_hits>=20" seems a bit ad-hoc, although not completely unreasonable. Is the "n-layers with hit>X" not enough criteria?

Note that here, you are _not_ referring to a feature of the event building. I assume that you saw it in the slack message that I linked above. This is an additional selection criterium that I used to improve the energy resolution. At that point, the _energy per shower_ is simply the sum of all triggered channels. No correction for chips that are not present in the event, or for masked channels. Yes, `n-layers with hit>X` could have served the same purpose (picking only events where not too many chips are not taking part). To be honest, I just took the first approach that came to my mind that removed the plateau towards lower energies.

**Comment by airqui** [comment]
I think that all is now understood, right ? Is there any more feedback expected before accepting the PR ?

**Comment by kunathj** [comment]
> Currently the merge_delta is a single number for both within-chip and between-chips. Maybe two different steering numbers would have been the better choice.

It is still only a single steering number. Not sure if that's ok (but would only be problematic in retriggering cycles. And any good analysis should anyways filter those out).

Could anyways be easily implemented later.

I think we left enough time for anyone else to give feedback. So whenever you're ok with it, hit the merge button.

**Comment by kunathj** [comment]
For more information on empty events and within-chip merging, let me refer you to my contribution to the [Si-ECAL Pre-CALICE meeting](https://indico.ific.uv.es/event/6578/contributions/18055/), presented yesterday.

**Pull request merged**
