### PR TITLE
Eventbuilding: Speedup, bug fixes and new features

### PR DESCRIPTION
**Pull request by kunathj**
This version is now significantly faster than what I previously implemented.
On the way there, I found and fixed some serious bugs.
A test-build.root file that I produced (from DESY TB data) shows a nice energy spectrum with the expected bump at 1 (2, 3) MIP.

Some additional branches and histograms are now saved in the rootfile.
I will show more details on this in the meeting tomorrow.

### CODE REVIEW

**Comment by kunathj** [comment]
@garcahec pointed out that this code currently only works for python3 (I'm using `source /cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-centos7-gcc10-opt/setup.sh`, which provides a python3).
I'll try to make the code python2&3 compatible, together with implementing the additional changes discussed today.

**Comment by kunathj** [comment]
Obviously this code should run with the current iLCSoft release (` /cvmfs/ilc.desy.de/sw/x86_64_gcc82_centos7/v02-02-03/init_ilcsoft.sh`). As that one ships python2 ROOT bindings, I fixed the python2 incompatibilities. (Note that those were already introduced before this PR).
A downside is that the eventbuilding takes 5 times longer on python2. As can be seen from the profiling screenshots below, creating the numpy arrays in the python2 code just takes much longer. Given these circumstances, I will aim to keep the code compatible with python2 (iLCSoft standard) and python3 (speed).
Should I add a printout line that warns python2-users that they could be much faster by switching to python3, or is this overkill? I like the idea, but would appreciate feedback.

@airqui @garcahec

## Python 2 
image

## Python 3
image

**Comment by airqui** [comment]
@kunathj 
Thanks for the update to make it comaptible with python 2.
It is a good idea to keep the possibility to use python3 and even show the message to the user as you propose.
I am not sure of the timeline of this, but eventually  ILCSoft will migrate to python3.

Tell me when you are happy with the changes so I can accept the PR

**Comment by airqui** [comment]
If it is slower.. that's life.

**Comment by airqui** [comment]
Is the python2 vs python3 issue already addressed in this request ?
Can you perform the request in the new branch ?


Happy new year :) 
@kunathj

**Comment by kunathj** [comment]
Sorry, I did not catch this notification..
> Is the python2 vs python3 issue already addressed in this request ? Can you perform the request in the new branch ?

Yes, 505fba201c602fca517188022f397006de8ae931 solved the py2-incompatibility.

#22 targets the analysis branch and includes the commits from here as well as more work. This PR is thus no longer needed.

**Pull request closed without merging**
